
var createCategoria = "CREATE TABLE IF NOT EXISTS CATEGORIA (ID INTEGER PRIMARY KEY AUTOINCREMENT, DESCRIPCION TEXT);";
var createContenido = "CREATE TABLE IF NOT EXISTS CONTENIDO (ID INTEGER PRIMARY KEY AUTOINCREMENT, IDCATEGORIA INTEGER, NUMECONTENIDO INTEGER, DESCRIPCION TEXT);";

var selectAllStatement = "SELECT * FROM CATEGORIA";
var selectOneContenido = "SELECT * FROM CONTENIDO WHERE id = ?";

var dropStatement = "DROP TABLE CATEGORIA";
var dropContenido = "DROP TABLE CONTENIDO";